
# Sesión 3: Matrices 
**Fecha:** 02/09 – 6pm  
**Tema central:** operaciones con matrices, propiedades, determinantes, inversas y solución de sistemas de ecuaciones.

---

Este cuadernillo es tu guía completa para la tercera sesión de matemáticas en el curso Introducción a la Computación Cuántica.  
La idea es que lo uses como **libro de consulta**: contiene teoría, ejemplos resueltos, ejercicios propuestos y un toque de aplicaciones en cuántica.



# 1.  Motivación y contexto
Las matrices son el lenguaje natural de:
- **Álgebra lineal**: permiten representar sistemas de ecuaciones lineales y transformaciones lineales en espacios vectoriales.  
- **Geometría**: representan rotaciones, reflexiones, dilataciones y proyecciones.  
- **Computación cuántica**: los estados cuánticos se modelan como **vectores complejos**, y las **puertas cuánticas** como matrices unitarias que transforman estos vectores.  


# 2. Definición y tipos de matrices

Una **matriz** es un arreglo rectangular de números (reales o complejos) ordenados en **filas** y **columnas**.

- Notación: una matriz de $m$ filas y $n$ columnas se llama **matriz $m \times n$**.
- Los números que la forman se llaman **elementos** de la matriz.
- Se denotan como $a_{ij}$, donde:
  - $i$ = número de fila.
  - $j$ = número de columna.

Ejemplo:

$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$

Aquí:
- $A$ es una matriz de **2×3**.  
- $a_{11} = 1$, $a_{12} = 2$, $a_{23} = 6$.


In [1]:

import numpy as np

# Definición de una matriz 2x3
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Matriz A:\n", A)
print("Dimensión de A:", A.shape)  # (filas, columnas)

# Acceso a elementos
print("Elemento a11 =", A[0, 0])
print("Elemento a23 =", A[1, 2])



Matriz A:
 [[1 2 3]
 [4 5 6]]
Dimensión de A: (2, 3)
Elemento a11 = 1
Elemento a23 = 6



## Tipos especiales de matrices

1. **Matriz fila:** una sola fila.  
   Ejemplo: $[1, 2, 3]$ 

2. **Matriz columna:** una sola columna.  
   Ejemplo:  
   $
   \begin{bmatrix}
   1 \\
   2 \\
   3
   \end{bmatrix}
   $

3. **Matriz cuadrada:** misma cantidad de filas y columnas ($n \times n$).  
    Ejemplo (n=3):
    $
    A = \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9
    \end{bmatrix}
    $

4. **Matriz diagonal:** solo tiene valores distintos de cero en la diagonal principal.  
    Ejemplo:
    $
    A = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 5 & 0 \\
    0 & 0 & 9
    \end{bmatrix}
    $

5. **Matriz triangular**
- **Triangular superior**: todos los elementos debajo de la diagonal principal son cero.  
    $
    T_s = \begin{bmatrix}
    1 & 4 & 2 \\
    0 & -3 & 5 \\
    0 & 0 & 6
    \end{bmatrix}
    $

- **Triangular inferior**: todos los elementos encima de la diagonal principal son cero.  
    $
    T_i = \begin{bmatrix}
    2 & 0 & 0 \\
    -1 & 3 & 0 \\
    4 & 5 & -2
    \end{bmatrix}
    $

    Estas matrices son importantes porque simplifican el cálculo de determinantes y aparecen en factorizaciones.

6. **Matriz identidad:** matriz diagonal con todos 1’s.  
    Ejemplo:
    $
    A = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
    \end{bmatrix}
    $

7. **Matriz nula:** todos sus elementos son cero.  
    Ejemplo:
    $
    A = \begin{bmatrix}
    0 & 0 & 0 \\
    0 & 0 & 0 \\
    0 & 0 & 0
    \end{bmatrix}
    $

8. **Matriz compleja**
    Matriz con entradas en los números complejos $\mathbb{C}$.  

    Ejemplo:  
    $
    A = \begin{bmatrix}
    1+i & 2 \\
    -3i & 4
    \end{bmatrix}
    $

    Casos relevantes en álgebra lineal y computación cuántica:  
    - **Hermítica**: $A = A^\dagger$ (igual a su conjugada transpuesta).  
    - **Unitaria**: $U^\dagger U = I$ (representa una puerta cuántica).  


In [2]:

# Ejemplos de tipos de matrices
fila = np.array([[1, 2, 3]])
columna = np.array([[1], [2], [3]])
cuadrada = np.array([[1, 2], [3, 4]])
identidad = np.eye(3)
nula = np.zeros((2, 2))
diagonal = np.diag([2, 5, 7])

print("Matriz fila:\n", fila)
print("Matriz columna:\n", columna)
print("Matriz cuadrada:\n", cuadrada)
print("Matriz identidad:\n", identidad)
print("Matriz nula:\n", nula)
print("Matriz diagonal:\n", diagonal)


Matriz fila:
 [[1 2 3]]
Matriz columna:
 [[1]
 [2]
 [3]]
Matriz cuadrada:
 [[1 2]
 [3 4]]
Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz nula:
 [[0. 0.]
 [0. 0.]]
Matriz diagonal:
 [[2 0 0]
 [0 5 0]
 [0 0 7]]



# 3. Operaciones básicas con matrices

Las matrices permiten realizar operaciones que generalizan las de los números reales. 

## 3.1. Suma y resta de matrices
- Solo se pueden sumar o restar matrices de la **misma dimensión**.  
- La operación se hace **elemento a elemento**:  

$
(A + B)_{ij} = a_{ij} + b_{ij}
$
$
(A - B)_{ij} = a_{ij} - b_{ij}
$

**Propiedades:**
1. Conmutativa: $A + B = B + A$.  
2. Asociativa: $(A + B) + C = A + (B + C)$.  
3. Existe matriz nula: $A + 0 = A$. 

In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A =\n", A)
print("B =\n", B)
print("A + B =\n", A + B)
print("A - B =\n", A - B)


A =
 [[1 2]
 [3 4]]
B =
 [[5 6]
 [7 8]]
A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]


## 3.2. Multiplicación por un escalar
Multiplicar una matriz por un número real o complejo significa multiplicar **cada elemento**:  

$
(\alpha A)_{ij} = \alpha \cdot a_{ij}
$

In [4]:
alpha = 3
print("3 * A =\n", alpha * A)

beta = 2 + 1j
print("(2+i) * A =\n", beta * A)

3 * A =
 [[ 3  6]
 [ 9 12]]
(2+i) * A =
 [[2.+1.j 4.+2.j]
 [6.+3.j 8.+4.j]]



## 3.3. Multiplicación de matrices
La multiplicación de matrices **NO es elemento a elemento** (pero sí existe un producto elemento a elemento, se llama Hadamard y se usa en machine learning).  

### Definición:
Si $A$ es de dimensión $m \times n$ y $B$ es de dimensión $n \times p$,  
entonces el producto $AB$ es una matriz de dimensión $m \times p$.  

¡El número de columnas de A y el número de filas de B deben ser el mismo!

$
(AB)_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}
$

Interpretación: fila de $A$ × columna de $B$.


In [5]:
# Ejemplo: producto de una matriz 2x3 por una 3x2
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 0],
              [0, 1],
              [1, 1]])

print("A =\n", A)
print("B =\n", B)
print("A @ B =\n", A @ B)  # @ es el operador de producto matricial

A =
 [[1 2 3]
 [4 5 6]]
B =
 [[1 0]
 [0 1]
 [1 1]]
A @ B =
 [[ 4  5]
 [10 11]]



## 3.4. Propiedades del producto matricial
1. **Asociatividad:** $A(BC) = (AB)C$.  
2. **Distributividad:** $A(B+C) = AB + AC$.  
3. **No conmutativa:** en general, $AB \neq BA$.  

Esto es muy importante en **computación cuántica**: el orden de las puertas (matrices) afecta el resultado.  


## 3.5. Producto de una matriz por un vector
Los vectores se pueden ver como matrices columna.  

Si $A$ es $m \times n$ y $x$ es un vector $n \times 1$,  
entonces $Ax$ es un vector $m \times 1$.  

En computación cuántica, esto es exactamente cómo una **puerta cuántica** (matriz unitaria) transforma un **estado cuántico** (vector complejo).


In [6]:
# Ejemplo: matriz 2x2 aplicada a un vector columna
A = np.array([[0, 1],
              [1, 0]])  # Matriz de Pauli-X (NOT cuántico)
x = np.array([[1],
              [0]])     # Estado |0>

print("A =\n", A)
print("x =\n", x)
print("A @ x =\n", A @ x)  # Resultado: estado |1>

A =
 [[0 1]
 [1 0]]
x =
 [[1]
 [0]]
A @ x =
 [[0]
 [1]]


## Ejercicios de Operaciones de matrices:

1. Calcula la suma y el producto (si existen) de las matrices:
$$
A = \begin{bmatrix} 1 & -2 & 0 \\ 3 & 1 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 2 & 0 \\ -1 & 3 \\ 4 & 5 \end{bmatrix}.
$$
Explica por qué $BA$ no está definido.

---

2. Demuestra con un ejemplo que en general $$AB \neq BA$$, pero que sí se cumple:
$$A(B+C) = AB + AC.$$

---

3. Considera las matrices
$$
C = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}, \quad
D = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}.
$$
- Calcula $CD$ y $DC$.  
- Interpreta estas matrices como transformaciones en el plano (reflexiones respecto a los ejes).  

---

4. Sea la matriz de rotación en el plano
$$
R(\theta) = \begin{bmatrix}
\cos\theta & -\sin\theta \\
\sin\theta & \cos\theta
\end{bmatrix}.
$$
- Calcula $$R\left(\tfrac{\pi}{4}\right) \begin{bmatrix}1 \\ 0\end{bmatrix}$$ y dibuja el resultado.  
- Demuestra que $$R(\theta_1)R(\theta_2) = R(\theta_1 + \theta_2)$$.

---

5. Usa Python para verificar las siguientes propiedades con matrices al azar:
- $ (AB)^T = B^T A^T $  
- $ A(B+C) = AB + AC $  
- $ (kA)B = k(AB) $  

---

6. (Reto) ¿Es posible que dos matrices cuadradas distintas $A$ y $B$ cumplan que $AB = BA$?  
Si es que sí, da un ejemplo. Si no, demuestra por qué.



# 4. Transpuesta, Conjugada y Adjunta

## 4.1. Transpuesta de una matriz
La **transpuesta** de una matriz $A$ se denota $A^T$ y se obtiene **intercambiando filas por columnas**:

- Si $A = [a_{ij}]$ es de dimensión $m \times n$,  
  entonces $A^T = [a_{ji}]$ es de dimensión $n \times m$.

Ejemplo:

$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}, \quad
A^T = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$

**Propiedades:**
1. $(A^T)^T = A$
2. $(A+B)^T = A^T + B^T$
3. $(AB)^T = B^T A^T$


In [7]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("A =\n", A)
print("A^T =\n", A.T)

A =
 [[1 2 3]
 [4 5 6]]
A^T =
 [[1 4]
 [2 5]
 [3 6]]


## 4.2. Conjugada de una matriz
Si los elementos de $A$ son complejos, la **conjugada** $\overline{A}$ se obtiene reemplazando cada elemento por su conjugado.

Ejemplo:

$
A = \begin{bmatrix}
1+i & 2 \\
-3i & 4
\end{bmatrix}, \quad
\overline{A} = \begin{bmatrix}
1-i & 2 \\
3i & 4
\end{bmatrix}
$

In [8]:
A = np.array([[1+1j, 2],
              [-3j, 4]])

print("A =\n", A)
print("Conjugada(A) =\n", np.conjugate(A))

A =
 [[ 1.+1.j  2.+0.j]
 [-0.-3.j  4.+0.j]]
Conjugada(A) =
 [[ 1.-1.j  2.-0.j]
 [-0.+3.j  4.-0.j]]


## 4.3. Conjugada transpuesta (o Dagger)
La **conjugada transpuesta** de $A$ se denota $A^\dagger$ y se define como:

$A^\dagger = \overline{A^T} = (\overline{A})^T$

Ejemplo:

$
A = \begin{bmatrix}
1+i & 2 \\
-3i & 4
\end{bmatrix}, \quad
A^\dagger = \begin{bmatrix}
1-i & 3i \\
2 & 4
\end{bmatrix}
$

**Importancia:**
- $A$ es **Hermítica** si $A^\dagger = A$.
- $U$ es **Unitaria** si $U^\dagger U = I$.


## 4.4. Matriz adjunta clásica (matriz de cofactores transpuesta)

La **adjunta clásica** (también llamada *adjunto* de $A$), denotada $\text{adj}(A)$, se define como:

1. Calcular la **matriz de cofactores** de $A$.  
2. Tomar su **transpuesta**.

---

### Matriz de cofactores
Dada una matriz $A = [a_{ij}]$ de tamaño $n \times n$, el **cofactor** de la entrada $a_{ij}$ se define como:

$$
C_{ij} = (-1)^{i+j} \det(M_{ij})
$$

donde $M_{ij}$ es la submatriz que se obtiene **eliminando la fila $i$ y la columna $j$** de $A$.

- La **matriz de cofactores** es:
$$
\text{Cof}(A) = [C_{ij}]
$$

---

### Definición de adjunta
La **adjunta** de $A$ se obtiene como la **transpuesta** de la matriz de cofactores:

$$
\text{adj}(A) = (\text{Cof}(A))^T
$$

---

### Ejemplo para $2 \times 2$
Si
$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix},
$$
entonces:

- $C_{11} = (+1)\det([d]) = d$  
- $C_{12} = (-1)\det([c]) = -c$  
- $C_{21} = (-1)\det([b]) = -b$  
- $C_{22} = (+1)\det([a]) = a$

Por lo tanto:
$$
\text{Cof}(A) = \begin{bmatrix} d & -c \\ -b & a \end{bmatrix},
\quad
\text{adj}(A) = (\text{Cof}(A))^T = \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

---

### Relación con la inversa
Si $\det(A) \neq 0$, la inversa de $A$ se calcula como:

$$
A^{-1} = \frac{1}{\det(A)} \, \text{adj}(A)
$$



# Ejercicios propuestos:

## 1. Transpuesta
Sea
$
A = \begin{bmatrix}
1 & 2 & -1 \\
0 & 3 & 4
\end{bmatrix}, \quad
B = \begin{bmatrix}
2 & -3 \\
1 & 0 \\
-2 & 5
\end{bmatrix}.
$
- Calcula $A^T$ y $B^T$.  
- Verifica que $(AB)^T = B^T A^T$.

## 2. Conjugada
Sea
$
C = \begin{bmatrix}
2+i & -3i \\
4 & 1-2i
\end{bmatrix}.
$
- Calcula la conjugada $\overline{C}$.  
- Calcula la transpuesta $C^T$.  
- Calcula el conjugado transpuesto $C^\dagger$.

## 3. Hermiticidad
Una matriz $H$ es **hermítica** si $H^\dagger = H$.  
Determina si las siguientes matrices son hermíticas:

a)  
$
H_1 = \begin{bmatrix}
2 & i \\
-i & 3
\end{bmatrix}
$

b)  
$
H_2 = \begin{bmatrix}
1 & 1+i \\
1-i & 2
\end{bmatrix}
$

## 4. Unitariedad
Una matriz $U$ es **unitaria** si $U^\dagger U = I$.  
Verifica si la siguiente matriz es unitaria:

$
U = \frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
-1 & 1
\end{bmatrix}
$

## 5. Adjunta clásica en 3x3
Sea
$
B = \begin{bmatrix}
1 & 0 & 2 \\
-1 & 3 & 1 \\
0 & 2 & -2
\end{bmatrix}.
$
- Calcula la matriz de cofactores de $B$.  
- Obtén $\text{adj}(B)$.  
- Verifica que $B \cdot \text{adj}(B) = \det(B) I$.

---

## 6. Reto
Prueba que, para cualquier matriz cuadrada $A$ de orden $n$:
$$
A \cdot \text{adj}(A) = \text{adj}(A) \cdot A = \det(A) I_n
$$
Pista: usa la expansión por cofactores del detemrinante.


# 5. Bloque 5: Determinantes

## 5.1. Definición del determinante
El **determinante** es un número asociado a una matriz cuadrada que resume información clave sobre ella:
- Nos dice si la matriz es invertible ($\det(A) \neq 0$).  
- Tiene interpretación geométrica (área, volumen, orientación).  
- Es fundamental para resolver sistemas de ecuaciones.

## 5.2. Determinante de una matriz $2 \times 2$
Si
$
A = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix},
$
entonces:

$
\det(A) = ad - bc
$

**Ejemplo:**
$
A = \begin{bmatrix}
2 & 3 \\
1 & 4
\end{bmatrix}, \quad
\det(A) = (2)(4) - (3)(1) = 8 - 3 = 5
$

## 5.3. Determinante de una matriz $3 \times 3$ (Regla de Sarrus)

Sea
$
B = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix},
$

la regla de Sarrus dice:

$
\det(B) = aei + bfg + cdh - ceg - bdi - afh
$

**Ejemplo:**

$
B = \begin{bmatrix}
1 & 2 & 3 \\
0 & 4 & 5 \\
1 & 0 & 6
\end{bmatrix}
$

$
\det(B) = (1)(4)(6) + (2)(5)(1) + (3)(0)(0) - (3)(4)(1) - (2)(0)(6) - (1)(5)(0)
= 24 + 10 + 0 - 12 - 0 - 0 = 22
$

## 5.4. Determinantes por cofactores (definición general)

Para una matriz cuadrada $A = [a_{ij}]$, se define:

$
\det(A) = \sum_{j=1}^n (-1)^{i+j} a_{ij} \det(M_{ij})
$

donde $M_{ij}$ es la submatriz que se obtiene eliminando la fila $i$ y columna $j$.  
Esto se conoce como **expansión por cofactores**.

## 5.5. Interpretación geométrica

- En $\mathbb{R}^2$: El determinante de una matriz $2 \times 2$ representa el **área con signo** del paralelogramo formado por sus columnas.  
- En $\mathbb{R}^3$: El determinante de una matriz $3 \times 3$ representa el **volumen con signo** del paralelepípedo formado por sus columnas.  
- Si $\det(A) = 0$, significa que las columnas de $A$ son **linealmente dependientes** (colapsan en una dimensión menor).

## 5.6. Propiedades fundamentales del determinante

1. $\det(I_n) = 1$  
2. $\det(A^T) = \det(A)$  
3. Si $A$ tiene una fila (o columna) de ceros, $\det(A) = 0$  
4. Si dos filas (o columnas) son proporcionales, $\det(A) = 0$  
5. $\det(AB) = \det(A)\det(B)$  
6. Si $k$ es un escalar, $\det(kA) = k^n \det(A)$ para $A$ de tamaño $n \times n$  
7. $A$ es invertible $\iff \det(A) \neq 0$


# Ejercicios de Determinantes

## 1. Determinante $2 \times 2$
Sea 
$
A = \begin{bmatrix}
3 & -2 \\
5 & 4
\end{bmatrix}.
$
- Calcula $\det(A)$.  
- Interpreta geométricamente el resultado como el área con signo de un paralelogramo.

---

## 2. Determinante $3 \times 3$ (Regla de Sarrus)
Sea 
$
B = \begin{bmatrix}
1 & 2 & 3 \\
0 & -1 & 4 \\
2 & 1 & 0
\end{bmatrix}.
$
- Calcula $\det(B)$ usando la **regla de Sarrus**.

---

## 3. Expansión por cofactores
Sea 
$
C = \begin{bmatrix}
2 & 0 & 1 \\
3 & 4 & -1 \\
1 & -2 & 5
\end{bmatrix}.
$
- Calcula $\det(C)$ expandiendo por la **primera fila**.  
- Verifica que obtienes el mismo resultado si expandes por la **segunda columna**.

---

## 4. Interpretación geométrica
Considera las columnas de la matriz
$
D = \begin{bmatrix}
2 & 1 \\
1 & 3
\end{bmatrix}
$
como vectores en $\mathbb{R}^2$.  
- Dibuja el paralelogramo formado por $(2,1)$ y $(1,3)$.  
- Calcula su área usando $\det(D)$.  
- ¿Qué ocurre si cambias el orden de las columnas?

---

## 5. Propiedad $\det(A^T) = \det(A)$
Sea 
$
E = \begin{bmatrix}
1 & 4 & 2 \\
0 & -3 & 5 \\
7 & 1 & 2
\end{bmatrix}.
$
- Calcula $\det(E)$.  
- Calcula $\det(E^T)$ y verifica la igualdad.

---

## 6. Propiedad: fila de ceros
Sea 
$
F = \begin{bmatrix}
1 & 2 & 3 \\
0 & 0 & 0 \\
4 & 5 & 6
\end{bmatrix}.
$
- Calcula $\det(F)$.  
- Explica por qué el resultado tiene sentido.

---

## 7. Propiedad: proporcionalidad de filas
Sea 
$
G = \begin{bmatrix}
2 & 4 \\
3 & 6
\end{bmatrix}.
$
- Calcula $\det(G)$.  
- Explica por qué el resultado refleja dependencia lineal entre las filas.

---

## 8. Propiedad: multiplicación
Sea 
$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}, \quad
B = \begin{bmatrix}
0 & 1 \\
-1 & 0
\end{bmatrix}.
$
- Calcula $\det(A)$, $\det(B)$ y $\det(AB)$.  
- Verifica la propiedad $\det(AB) = \det(A)\det(B)$.

---

## 9. Propiedad: factor escalar
Sea 
$
H = \begin{bmatrix}
1 & 0 \\
2 & 3
\end{bmatrix}.
$
- Calcula $\det(H)$.  
- Calcula $\det(2H)$.  
- Verifica que $\det(kA) = k^n \det(A)$ para $n=2$.

---

## 10. Criterio de invertibilidad
Sea 
$
J = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}.
$
- Calcula $\det(J)$.  
- ¿Es $J$ invertible? ¿Por qué?

# 6. Inversas de matrices

## 6.1. Definición de inversa
Sea $A$ una matriz cuadrada de orden $n$.

- Decimos que $A$ es **invertible** (o no singular) si existe una matriz $B$ tal que:
$$
AB = BA = I_n
$$
En ese caso, $B$ se llama la **inversa de $A$** y se denota $A^{-1}$.

- Condición: $A$ es invertible si y solo si $\det(A) \neq 0$.


## 6.2. Fórmula con la adjunta clásica
Si $A$ es invertible, se cumple:
$$
A^{-1} = \frac{1}{\det(A)} \, \text{adj}(A)
$$
donde $\text{adj}(A)$ es la matriz adjunta clásica (traspuesta de la matriz de cofactores).

### Ejemplo
Sea
$$
A = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix}
$$

1. Determinante: $\det(A) = (2)(4) - (3)(1) = 5$.  
2. Adjunta:
$$
\text{adj}(A) = \begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix}
$$  
3. Inversa:
$$
A^{-1} = \frac{1}{5} \begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix}
$$


## 6.3. Método de Gauss-Jordan
Otra forma de calcular $A^{-1}$ es usando operaciones elementales:

1. Formar la matriz aumentada $[A \,|\, I]$.  
2. Aplicar operaciones elementales por filas hasta transformar la izquierda en $I$.  
3. La derecha se convierte en $A^{-1}$.

### Ejemplo
Sea
$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

Matriz aumentada:
$$
\left[ \begin{array}{cc|cc}
1 & 2 & 1 & 0 \\
3 & 4 & 0 & 1
\end{array}\right]
$$

1. $F_2 \to F_2 - 3F_1$:  
$$
\left[ \begin{array}{cc|cc}
1 & 2 & 1 & 0 \\
0 & -2 & -3 & 1
\end{array}\right]
$$

2. $F_2 \to -\tfrac{1}{2} F_2$:  
$$
\left[ \begin{array}{cc|cc}
1 & 2 & 1 & 0 \\
0 & 1 & \tfrac{3}{2} & -\tfrac{1}{2}
\end{array}\right]
$$

3. $F_1 \to F_1 - 2F_2$:  
$$
\left[ \begin{array}{cc|cc}
1 & 0 & -2 & 1 \\
0 & 1 & \tfrac{3}{2} & -\tfrac{1}{2}
\end{array}\right]
$$

Por lo tanto:
$$
A^{-1} = \begin{bmatrix} -2 & 1 \\ \tfrac{3}{2} & -\tfrac{1}{2} \end{bmatrix}
$$


## 6.4. Propiedades de la inversa
1. $(A^{-1})^{-1} = A$  
2. $(AB)^{-1} = B^{-1} A^{-1}$  
3. $(A^T)^{-1} = (A^{-1})^T$  
4. $(A^\dagger)^{-1} = (A^{-1})^\dagger$


## 6.5. Aplicación: resolución de sistemas lineales
Un sistema lineal de $n$ ecuaciones con $n$ incógnitas puede escribirse como:
$$
AX = b
$$

Si $A$ es invertible, la solución única es:
$$
X = A^{-1} b
$$

### Ejemplo
Resolver:
$$
\begin{cases}
2x + 3y = 5 \\
x + 4y = 6
\end{cases}
$$

Matriz:
$
A = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix}, \quad
b = \begin{bmatrix} 5 \\ 6 \end{bmatrix}
$

Ya vimos que:
$
A^{-1} = \frac{1}{5}\begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix}
$

Entonces:
$$
X = A^{-1} b = \frac{1}{5}\begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix}\begin{bmatrix} 5 \\ 6 \end{bmatrix}
= \frac{1}{5}\begin{bmatrix} 20 - 18 \\ -5 + 12 \end{bmatrix}
= \frac{1}{5}\begin{bmatrix} 2 \\ 7 \end{bmatrix}
= \begin{bmatrix} \tfrac{2}{5} \\ \tfrac{7}{5} \end{bmatrix}
$$


# Ejercicios propuestos - Inversa de matrices

---

## 1. Cálculo por adjunta
Calcula la inversa de la matriz (si existe) usando la fórmula con la adjunta clásica:

$$
A = \begin{bmatrix}
2 & 1 \\
5 & 3
\end{bmatrix}
$$

---

## 2. Cálculo por Gauss–Jordan
Encuentra la inversa de la matriz $B$ aplicando el método de Gauss–Jordan:

$$
B = \begin{bmatrix}
1 & 2 & 1 \\
0 & 1 & 3 \\
2 & -1 & 1
\end{bmatrix}
$$

---

## 3. Verificación de propiedades
Sea 
$$
C = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}, \quad
D = \begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix}
$$  

a) Calcula $C^{-1}$ y $D^{-1}$.  
b) Verifica que $(CD)^{-1} = D^{-1} C^{-1}$.  

---

## 4. Aplicación en sistemas lineales
Resuelve el sistema $AX = b$ usando inversa de matrices:

$$
A = \begin{bmatrix}
2 & -1 \\
1 & 1
\end{bmatrix}, \quad
b = \begin{bmatrix}
3 \\
2
\end{bmatrix}
$$

---

## 5. Reto: matriz no invertible
Sea
$$
E = \begin{bmatrix}
2 & 4 \\
1 & 2
\end{bmatrix}
$$

a) Calcula $\det(E)$.  
b) Explica por qué $E$ no es invertible.  
c) Interpreta geométricamente qué significa esto respecto al área de la transformación lineal definida por $E$.  


# 7. Matriz escalonada y reducción por Gauss–Jordan

## 7.1. Definición de matriz escalonada

Una matriz está en **forma escalonada por filas (row echelon form, REF)** si cumple:

1. Todas las filas de ceros están al final.  
2. En cada fila no nula, el primer número distinto de cero (llamado **pivote**) está a la derecha del pivote de la fila anterior.  
3. Todos los elementos debajo de un pivote son cero.  

### Ejemplo de matriz en forma escalonada

$
\begin{bmatrix}
1 & 2 & -1 & 3 \\
0 & 1 & 4 & -2 \\
0 & 0 & 0 & 5 \\
0 & 0 & 0 & 0
\end{bmatrix}
$

- El pivote de la primera fila está en la columna 1.  
- El pivote de la segunda fila está en la columna 2 (a la derecha del anterior).  
- La tercera fila tiene un pivote en la columna 4, que también está más a la derecha.  
- La última fila es nula y está al final.  

### Ejemplo de matriz que **NO** está en forma escalonada

$
\begin{bmatrix}
0 & 2 & 1 \\
1 & 3 & 4 \\
0 & 0 & 5
\end{bmatrix}
$

- El primer elemento no nulo de la primera fila está en la columna 2.  
- Pero la segunda fila tiene un pivote en la columna 1 (a la izquierda).  
- Esto rompe la regla: *cada pivote debe estar a la derecha del de la fila anterior*.  

## 7.2. Forma escalonada reducida
Una matriz está en **forma escalonada reducida por filas (reduced row echelon form, RREF)** si además:

1. Cada pivote vale 1.  
2. En la columna de cada pivote, todos los demás elementos son cero.  

### Ejemplo de matriz en RREF

$
\begin{bmatrix}
1 & 0 & 2 & -1 \\
0 & 1 & 3 & 4 \\
0 & 0 & 0 & 0
\end{bmatrix}
$

- Los pivotes están en la columna 1 y 2, y ambos son **1**.  
- En la columna de cada pivote, todos los demás elementos son cero.  
- Cumple las condiciones de RREF.  


### Ejemplo de matriz que **NO** está en RREF

$
\begin{bmatrix}
1 & 2 & 0 \\
0 & 1 & 3 \\
0 & 0 & 0
\end{bmatrix}
$

- Los pivotes están en la columna 1 y 2, correctos.  
- En la columna del primer pivote (columna 1) solo hay ceros aparte del 1 (en este caso bien), pero en la columna del segundo pivote (columna 2) aparece un **2** en la primera fila.  
- Eso viola la condición: *cada columna con pivote debe tener solo un 1 y ceros en el resto de entradas*.  

## 7.3. Operaciones elementales por filas
Para llevar una matriz a REF o RREF, usamos **operaciones elementales**:

1. Intercambiar dos filas.  
2. Multiplicar una fila por un escalar no nulo.  
3. Sumar a una fila un múltiplo de otra.

## 7.4. Ejemplo: reducción a forma escalonada

Sea
$$
A = \begin{bmatrix}
1 & 2 & -1 \\
2 & 4 & -2 \\
3 & 6 & -3
\end{bmatrix}
$$

1. El pivote está en la posición $(1,1) = 1$.  
2. Eliminamos entradas debajo:  
   - $F_2 \to F_2 - 2F_1$  
   - $F_3 \to F_3 - 3F_1$  

Resultado:
$$
\begin{bmatrix}
1 & 2 & -1 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$$

Esto está en **forma escalonada**, y muestra que las filas son linealmente dependientes.

## 7.5. Ejemplo: forma escalonada reducida

Sea
$$
B = \begin{bmatrix}
1 & 2 & 1 \\
2 & 4 & 0 \\
3 & 6 & 1
\end{bmatrix}
$$

1. $F_2 \to F_2 - 2F_1$, $F_3 \to F_3 - 3F_1$:
$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & 0 & -2 \\
0 & 0 & -2
\end{bmatrix}
$$

2. $F_3 \to F_3 - F_2$:
$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & 0 & -2 \\
0 & 0 & 0
\end{bmatrix}
$$

3. Escalar $F_2 \to -\tfrac{1}{2}F_2$:
$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & 0 & 1 \\
0 & 0 & 0
\end{bmatrix}
$$

4. Eliminar arriba del pivote en columna 3: $F_1 \to F_1 - F_2$:
$$
\begin{bmatrix}
1 & 2 & 0 \\
0 & 0 & 1 \\
0 & 0 & 0
\end{bmatrix}
$$

Este es el **RREF** de $B$.

## 7.6. Rango de una matriz
El **rango** de una matriz es el número de pivotes en su forma escalonada reducida.  
Equivale a la dimensión del espacio generado por sus filas o columnas.

Ejemplo: en el $B$ anterior, hay 2 pivotes → $rango(B) = 2$.

## 7.7. Aplicación: resolución de sistemas lineales
Un sistema $AX = b$ se puede resolver reduciendo la matriz aumentada $[A|b]$ a RREF.

### Ejemplo
Sistema:
$$
\begin{cases}
x + 2y + z = 2 \\
2x + 4y + 2z = 4 \\
3x + 6y + 3z = 6
\end{cases}
$$

Matriz aumentada:
$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
2 & 4 & 2 & 4 \\
3 & 6 & 3 & 6
\end{array}
\right]
$$

Reduciendo:
$$
\left[
\begin{array}{ccc|c}
1 & 2 & 1 & 2 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{array}
\right]
$$

Este sistema tiene infinitas soluciones:
$$
x = 2 - 2y - z, \quad y, z \in \mathbb{R}
$$


# 8. Teorema de Rouché–Frobenius

Hasta ahora hemos visto:
- Cómo representar sistemas de ecuaciones lineales como $AX = b$.
- Cómo reducir matrices a forma escalonada.
- Cómo calcular el rango de una matriz.

La gran pregunta es: **¿cuándo un sistema $AX=b$ tiene solución?**

## 8.1. Enunciado del Teorema de Rouché–Frobenius
Sea $A$ la matriz de coeficientes de un sistema lineal y $[A|b]$ la matriz aumentada.  

1. El sistema $AX=b$ es **compatible** (tiene solución) si y solo si:
$$
\text{rango}(A) = \text{rango}([A|b])
$$

2. Si el sistema es compatible, entonces:
   - Si $\text{rango}(A) = n$ (número de incógnitas), la solución es **única**.  
   - Si $\text{rango}(A) < n$, el sistema tiene **infinitas soluciones** (parámetros libres).  


## 8.2. Interpretación
- El rango mide cuántas ecuaciones realmente **aportan información independiente**.  
- Si al añadir la columna de términos independientes $b$ no cambia el rango, significa que $b$ "encaja" en el espacio generado por las columnas de $A$ → el sistema tiene solución.  
- Si el rango aumenta al añadir $b$, entonces $b$ está fuera del espacio generado → el sistema es incompatible.  


## 8.3. Ejemplo 1: sistema compatible determinado
Sistema:
$$
\begin{cases}
x + y = 2 \\
x - y = 0
\end{cases}
$$

Matriz:
$
A = \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}, \quad
b = \begin{bmatrix} 2 \\ 0 \end{bmatrix}
$

Matriz aumentada:
$
[A|b] = \begin{bmatrix} 1 & 1 & 2 \\ 1 & -1 & 0 \end{bmatrix}
$

- $\text{rango}(A) = 2$  
- $\text{rango}([A|b]) = 2$  
- $n = 2$ → **solución única**.  

Resolviendo: $x=1, y=1$.  


## 8.4. Ejemplo 2: sistema compatible indeterminado
Sistema:
$$
\begin{cases}
x + y + z = 2 \\
2x + 2y + 2z = 4
\end{cases}
$$

Matriz:
$
A = \begin{bmatrix} 1 & 1 & 1 \\ 2 & 2 & 2 \end{bmatrix}, \quad
b = \begin{bmatrix} 2 \\ 4 \end{bmatrix}
$

Matriz aumentada:
$
[A|b] = \begin{bmatrix} 1 & 1 & 1 & 2 \\ 2 & 2 & 2 & 4 \end{bmatrix}
$

- $\text{rango}(A) = 1$ (la segunda fila es múltiplo de la primera).  
- $\text{rango}([A|b]) = 1$.  
- $n = 3$ → **infinitas soluciones** (2 parámetros libres).  


## 8.5. Ejemplo 3: sistema incompatible
Sistema:
$$
\begin{cases}
x + y = 1 \\
x + y = 2
\end{cases}
$$

Matriz:
$
A = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}, \quad
b = \begin{bmatrix} 1 \\ 2 \end{bmatrix}
$

Matriz aumentada:
$
[A|b] = \begin{bmatrix} 1 & 1 & 1 \\ 1 & 1 & 2 \end{bmatrix}
$

- $\text{rango}(A) = 1$  
- $\text{rango}([A|b]) = 2$  
- Los rangos no coinciden → **sistema incompatible** (sin solución).  


## 8.6. Resumen visual
- Si $\text{rango}(A) = \text{rango}([A|b]) = n$: solución única.  
- Si $\text{rango}(A) = \text{rango}([A|b]) < n$: infinitas soluciones.  
- Si $\text{rango}(A) \neq \text{rango}([A|b])$: sin solución.  

# Ejercicios propuestos - Teorema de Rouché–Frobenius

1. Determina las soluciones del sistema:

$$
\begin{cases}
x + y = 3 \\
2x - y = 1
\end{cases}
$$

---

2. Determina las soluciones del sistema:

$$
\begin{cases}
x + y + z = 1 \\
2x + 2y + 2z = 2
\end{cases}
$$

---

3. Determina las soluciones del sistema:

$$
\begin{cases}
x + y = 1 \\
x + y = 3
\end{cases}
$$

---

4. Clasifica cada uno de los siguientes sistemas usando el teorema de Rouché–Frobenius:

a)  
$$
\begin{cases}
x + 2y = 4 \\
2x + 4y = 8
\end{cases}
$$

b)  
$$
\begin{cases}
x - y + z = 0 \\
2x - 2y + 2z = 0 \\
x + y - z = 1
\end{cases}
$$

c)  
$$
\begin{cases}
x + y + z = 2 \\
2x + 2y + 2z = 5
\end{cases}
$$

---

5. Reto teórico

Demuestra que un sistema $AX=b$ es compatible si y solo si $b$ pertenece al **espacio columna** de $A$.